name: Test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - run: echo "Hello ${{github.event}}"
